import { Product } from '@/types';

const SVG_IMAGES = {
  mango: '/mango-burst.jpg',
  orange: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23FFF3E0"/><circle cx="300" cy="300" r="200" fill="%23FF70A6" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🍊</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%23FF70A6">Valencia Orange</text></svg>`,
  watermelon: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23FFEBEE"/><circle cx="300" cy="300" r="200" fill="%23FF4D6D" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🍉</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%23FF4D6D">Watermelon Splash</text></svg>`,
  pineapple: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23FFFDE7"/><circle cx="300" cy="300" r="200" fill="%23FFB703" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🍍</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%23FFB703">Pineapple Punch</text></svg>`,
  apple: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23F1F8E9"/><circle cx="300" cy="300" r="200" fill="%2370E000" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🍏</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%2370E000">Apple Fresh</text></svg>`,
  green: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23E8F5E9"/><circle cx="300" cy="300" r="200" fill="%2338B000" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🥬</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%2338B000">Green Detox</text></svg>`,
  lemon: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23FFFDE7"/><circle cx="300" cy="300" r="200" fill="%23FFC83D" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🍋</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%23EE9B00">Lemon Ginger</text></svg>`,
  strawberry: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23FCE4EC"/><circle cx="300" cy="300" r="200" fill="%23FF4D6D" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🍓</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%23FF4D6D">Strawberry Dream</text></svg>`,
  berry: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23F3E5F5"/><circle cx="300" cy="300" r="200" fill="%237209B7" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🫐</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%237209B7">Banana Berry</text></svg>`,
  chocolate: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23EFEBE9"/><circle cx="300" cy="300" r="200" fill="%236F1D1B" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🍫</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%236F1D1B">Chocolate Shake</text></svg>`,
  vanilla: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600"><rect width="600" height="600" fill="%23FFFDF8"/><circle cx="300" cy="300" r="200" fill="%23FFC83D" opacity="0.25"/><text x="50%" y="45%" dominant-baseline="middle" text-anchor="middle" font-size="130">🍦</text><text x="50%" y="68%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-weight="800" font-size="32" fill="%23FFC83D">Vanilla Shake</text></svg>`,
};

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'mango-burst',
    name: 'Mango Burst',
    slug: 'mango-burst',
    description: 'Sun-ripened Alphonso mangoes blended into a velvety, tropical elixir bursting with vitamins and natural sweetness.',
    category: 'Fruit Juices',
    price: 149,
    sizePrices: {
      '250ml': 149,
      '500ml': 249,
      '1L': 449,
    },
    ingredients: ['Fresh Alphonso Mango Pulp', 'Organic Coconut Water', 'Touch of Lime Juice', 'Natural Mint Extract'],
    nutrition: {
      calories: 160,
      vitaminC: '140% DV',
      sugar: '24g (Natural)',
      protein: '1.5g',
      carbs: '38g',
      fiber: '3.5g',
    },
    healthBenefits: ['Energy', 'Immunity', 'Refreshment'],
    tags: ['High Vitamin C', 'Top Seller', '100% Natural', 'No Added Sugar'],
    rating: 4.9,
    reviewCount: 324,
    image: SVG_IMAGES.mango,
    accentColor: '#FF9F1C',
    fruitType: 'mango',
    available: true,
    stock: 45,
    featured: true,
  },
  {
    id: 'orange-glow',
    name: 'Orange Glow',
    slug: 'orange-glow',
    description: 'Freshly cold-pressed Valencia oranges infused with turmeric and ginger for radiant skin and daily immunity boost.',
    category: 'Fruit Juices',
    price: 129,
    sizePrices: {
      '250ml': 129,
      '500ml': 219,
      '1L': 399,
    },
    ingredients: ['Valencia Orange Juice', 'Cold-Pressed Turmeric', 'Raw Ginger Extract', 'Lemon Zest'],
    nutrition: {
      calories: 120,
      vitaminC: '200% DV',
      sugar: '18g (Natural)',
      protein: '2g',
      carbs: '28g',
      fiber: '2.5g',
    },
    healthBenefits: ['Immunity', 'Energy', 'Detox'],
    tags: ['Immunity Booster', 'Cold Pressed', 'Antioxidants'],
    rating: 4.8,
    reviewCount: 215,
    image: SVG_IMAGES.orange,
    accentColor: '#FF70A6',
    fruitType: 'orange',
    available: true,
    stock: 60,
    featured: true,
  },
  {
    id: 'watermelon-splash',
    name: 'Watermelon Splash',
    slug: 'watermelon-splash',
    description: 'Ultra-hydrating seedless ruby watermelon cold-pressed with fresh basil leaves and a pinch of pink Himalayan salt.',
    category: 'Fruit Juices',
    price: 119,
    sizePrices: {
      '250ml': 119,
      '500ml': 199,
      '1L': 349,
    },
    ingredients: ['Seedless Watermelon', 'Fresh Basil Leaves', 'Lime Juice', 'Himalayan Pink Salt'],
    nutrition: {
      calories: 85,
      vitaminC: '45% DV',
      sugar: '14g (Natural)',
      protein: '1g',
      carbs: '20g',
      fiber: '1g',
    },
    healthBenefits: ['Hydration', 'Refreshment', 'Fitness'],
    tags: ['Low Calorie', 'Ultra Hydrating', 'Summer Special'],
    rating: 4.7,
    reviewCount: 189,
    image: SVG_IMAGES.watermelon,
    accentColor: '#FF4D6D',
    fruitType: 'watermelon',
    available: true,
    stock: 35,
    featured: true,
  },
  {
    id: 'pineapple-punch',
    name: 'Pineapple Punch',
    slug: 'pineapple-punch',
    description: 'Zesty Queen pineapple juice blended with passionfruit and coconut water for an instant tropical getaway in a bottle.',
    category: 'Fruit Juices',
    price: 139,
    sizePrices: {
      '250ml': 139,
      '500ml': 229,
      '1L': 419,
    },
    ingredients: ['Queen Pineapple', 'Passionfruit Nectar', 'Coconut Water', 'Chia Seeds'],
    nutrition: {
      calories: 140,
      vitaminC: '110% DV',
      sugar: '22g (Natural)',
      protein: '1.2g',
      carbs: '32g',
      fiber: '3g',
    },
    healthBenefits: ['Digestion', 'Energy', 'Immunity'],
    tags: ['Digestive Enzymes', 'Tropical', 'Chia Rich'],
    rating: 4.8,
    reviewCount: 162,
    image: SVG_IMAGES.pineapple,
    accentColor: '#FFB703',
    fruitType: 'pineapple',
    available: true,
    stock: 50,
  },
  {
    id: 'apple-fresh',
    name: 'Apple Fresh',
    slug: 'apple-fresh',
    description: 'Crisp Shimla green and red apples cold-pressed with a touch of cinnamon and elderflower.',
    category: 'Fruit Juices',
    price: 129,
    sizePrices: {
      '250ml': 129,
      '500ml': 219,
      '1L': 389,
    },
    ingredients: ['Shimla Red Apples', 'Granny Smith Green Apples', 'Cinnamon Extract', 'Lemon Juice'],
    nutrition: {
      calories: 110,
      vitaminC: '30% DV',
      sugar: '19g (Natural)',
      protein: '0.8g',
      carbs: '26g',
      fiber: '4g',
    },
    healthBenefits: ['Digestion', 'Detox', 'Refreshment'],
    tags: ['High Fiber', 'Pure Juice', 'No Preservatives'],
    rating: 4.6,
    reviewCount: 98,
    image: SVG_IMAGES.apple,
    accentColor: '#70E000',
    fruitType: 'lemon',
    available: true,
    stock: 40,
  },
  {
    id: 'green-detox',
    name: 'Green Detox',
    slug: 'green-detox',
    description: 'Powerhouse blend of organic kale, baby spinach, green apple, cucumber, celery, and lemon to cleanse and revitalize.',
    category: 'Detox',
    price: 159,
    sizePrices: {
      '250ml': 159,
      '500ml': 269,
      '1L': 489,
    },
    ingredients: ['Organic Kale', 'Baby Spinach', 'Crisp Cucumber', 'Celery Stalks', 'Green Apple', 'Cold-Pressed Lemon'],
    nutrition: {
      calories: 75,
      vitaminC: '160% DV',
      sugar: '9g (Low Sugar)',
      protein: '3g',
      carbs: '16g',
      fiber: '5g',
    },
    healthBenefits: ['Detox', 'Digestion', 'Immunity'],
    tags: ['Low Sugar', 'Alkalizing', 'Chlorophyll Boost', 'Keto Friendly'],
    rating: 4.9,
    reviewCount: 412,
    image: SVG_IMAGES.green,
    accentColor: '#38B000',
    fruitType: 'green',
    available: true,
    stock: 55,
    featured: true,
  },
  {
    id: 'cucumber-mint',
    name: 'Cucumber Mint',
    slug: 'cucumber-mint',
    description: 'Refreshing cucumber juice paired with spearmint leaves, aloe vera gel, and lime juice for ultimate cellular hydration.',
    category: 'Detox',
    price: 129,
    sizePrices: {
      '250ml': 129,
      '500ml': 219,
      '1L': 389,
    },
    ingredients: ['Fresh Cucumber', 'Spearmint Leaves', 'Organic Aloe Vera Gel', 'Key Lime Juice'],
    nutrition: {
      calories: 45,
      vitaminC: '40% DV',
      sugar: '4g (Ultra Low)',
      protein: '1g',
      carbs: '9g',
      fiber: '2g',
    },
    healthBenefits: ['Hydration', 'Detox', 'Refreshment'],
    tags: ['Zero Added Sugar', 'Aloe Vera Infused', 'Calming'],
    rating: 4.7,
    reviewCount: 144,
    image: SVG_IMAGES.green,
    accentColor: '#52B788',
    fruitType: 'lemon',
    available: true,
    stock: 30,
  },
  {
    id: 'lemon-ginger',
    name: 'Lemon Ginger',
    slug: 'lemon-ginger',
    description: 'Spicy and tangy wellness shot bottle combining cold-pressed lemons, fiery ginger root, cayenne pepper, and raw wildflower honey.',
    category: 'Detox',
    price: 139,
    sizePrices: {
      '250ml': 139,
      '500ml': 239,
      '1L': 429,
    },
    ingredients: ['Fresh Eureka Lemons', 'Raw Ginger Root', 'Wildflower Honey', 'Cayenne Pepper', 'Filtered Water'],
    nutrition: {
      calories: 90,
      vitaminC: '180% DV',
      sugar: '12g (Natural Honey)',
      protein: '0.5g',
      carbs: '22g',
      fiber: '1g',
    },
    healthBenefits: ['Immunity', 'Digestion', 'Energy'],
    tags: ['Metabolism Boost', 'Spicy Kick', 'Gut Health'],
    rating: 4.9,
    reviewCount: 278,
    image: SVG_IMAGES.lemon,
    accentColor: '#EE9B00',
    fruitType: 'lemon',
    available: true,
    stock: 48,
  },
  {
    id: 'spinach-glow',
    name: 'Spinach Glow',
    slug: 'spinach-glow',
    description: 'Rich dark leafy spinach, sweet green pear, kiwi, and spirulina algae for an iron-packed natural glow.',
    category: 'Detox',
    price: 149,
    sizePrices: {
      '250ml': 149,
      '500ml': 249,
      '1L': 449,
    },
    ingredients: ['Baby Spinach', 'Conference Pear', 'Fresh Kiwi', 'Organic Spirulina Powder', 'Coconut Water'],
    nutrition: {
      calories: 95,
      vitaminC: '130% DV',
      sugar: '11g (Natural)',
      protein: '3.5g',
      carbs: '21g',
      fiber: '4.5g',
    },
    healthBenefits: ['Detox', 'Immunity', 'Fitness'],
    tags: ['Superfood', 'Iron Rich', 'Spirulina Enhanced'],
    rating: 4.6,
    reviewCount: 86,
    image: SVG_IMAGES.green,
    accentColor: '#2D6A4F',
    fruitType: 'green',
    available: true,
    stock: 25,
  },
  {
    id: 'strawberry-dream',
    name: 'Strawberry Dream',
    slug: 'strawberry-dream',
    description: 'Creamy blend of organic strawberries, Greek yogurt, almond milk, chia seeds, and vanilla bean extract.',
    category: 'Smoothies',
    price: 169,
    sizePrices: {
      '250ml': 169,
      '500ml': 279,
      '1L': 499,
    },
    ingredients: ['Organic Strawberries', 'Greek Yogurt', 'Almond Milk', 'Chia Seeds', 'Natural Vanilla Bean'],
    nutrition: {
      calories: 210,
      vitaminC: '95% DV',
      sugar: '16g (Natural)',
      protein: '9g',
      carbs: '29g',
      fiber: '5g',
    },
    healthBenefits: ['Fitness', 'Energy', 'Refreshment'],
    tags: ['High Protein', 'Probiotic', 'Creamy & Delicious'],
    rating: 4.9,
    reviewCount: 390,
    image: SVG_IMAGES.strawberry,
    accentColor: '#FF4D6D',
    fruitType: 'strawberry',
    available: true,
    stock: 50,
    featured: true,
  },
  {
    id: 'banana-berry',
    name: 'Banana Berry',
    slug: 'banana-berry',
    description: 'Antioxidant-rich wild blueberries, blackberries, ripe Robusta banana, and oats protein smoothie.',
    category: 'Smoothies',
    price: 179,
    sizePrices: {
      '250ml': 179,
      '500ml': 289,
      '1L': 519,
    },
    ingredients: ['Wild Blueberries', 'Blackberries', 'Ripe Bananas', 'Rolled Oats', 'Almond Milk', 'Flaxseeds'],
    nutrition: {
      calories: 240,
      vitaminC: '60% DV',
      sugar: '19g (Natural)',
      protein: '8g',
      carbs: '42g',
      fiber: '7g',
    },
    healthBenefits: ['Energy', 'Fitness', 'Digestion'],
    tags: ['Antioxidant Bomb', 'Post Workout', 'Oats Powered'],
    rating: 4.8,
    reviewCount: 204,
    image: SVG_IMAGES.berry,
    accentColor: '#7209B7',
    fruitType: 'berry',
    available: true,
    stock: 40,
  },
  {
    id: 'mango-cream',
    name: 'Mango Cream',
    slug: 'mango-cream',
    description: 'Luxurious tropical smoothie made with Alphonso mangoes, coconut cream, cashew butter, and saffron strands.',
    category: 'Smoothies',
    price: 189,
    sizePrices: {
      '250ml': 189,
      '500ml': 299,
      '1L': 539,
    },
    ingredients: ['Alphonso Mango', 'Coconut Cream', 'Raw Cashew Butter', 'Kashmiri Saffron', 'Cardamom'],
    nutrition: {
      calories: 260,
      vitaminC: '120% DV',
      sugar: '23g (Natural)',
      protein: '5g',
      carbs: '36g',
      fiber: '4g',
    },
    healthBenefits: ['Energy', 'Refreshment'],
    tags: ['Decadent', 'Kashmiri Saffron', 'Rich & Creamy'],
    rating: 4.9,
    reviewCount: 175,
    image: SVG_IMAGES.mango,
    accentColor: '#FFB703',
    fruitType: 'mango',
    available: true,
    stock: 35,
  },
  {
    id: 'tropical-mix',
    name: 'Tropical Mix',
    slug: 'tropical-mix',
    description: 'Exotic blend of dragonfruit, papaya, guava, coconut water, and lime juice for pure beachside bliss.',
    category: 'Smoothies',
    price: 169,
    sizePrices: {
      '250ml': 169,
      '500ml': 279,
      '1L': 489,
    },
    ingredients: ['Red Dragonfruit', 'Ripe Papaya', 'Pink Guava', 'Tender Coconut Water', 'Lime Juice'],
    nutrition: {
      calories: 165,
      vitaminC: '150% DV',
      sugar: '18g (Natural)',
      protein: '2.5g',
      carbs: '35g',
      fiber: '5.5g',
    },
    healthBenefits: ['Immunity', 'Hydration', 'Digestion'],
    tags: ['Exotic Fruits', 'Gut Friendly', 'Vibrant Pink'],
    rating: 4.7,
    reviewCount: 132,
    image: SVG_IMAGES.strawberry,
    accentColor: '#F72585',
    fruitType: 'strawberry',
    available: true,
    stock: 45,
  },
  {
    id: 'chocolate-shake',
    name: 'Chocolate Shake',
    slug: 'chocolate-shake',
    description: 'Guilt-free artisanal shake crafted with Dutch cocoa powder, frozen banana, dates, pea protein, and oat milk.',
    category: 'Shakes',
    price: 199,
    sizePrices: {
      '250ml': 199,
      '500ml': 319,
      '1L': 569,
    },
    ingredients: ['Raw Dutch Cocoa Powder', 'Medjool Dates', 'Organic Plant Protein', 'Almond Butter', 'Creamy Oat Milk'],
    nutrition: {
      calories: 280,
      vitaminC: '15% DV',
      sugar: '15g (Date Sweetened)',
      protein: '18g',
      carbs: '38g',
      fiber: '6g',
    },
    healthBenefits: ['Fitness', 'Energy'],
    tags: ['18g Vegan Protein', 'Date Sweetened', 'Zero Dairy'],
    rating: 4.9,
    reviewCount: 310,
    image: SVG_IMAGES.chocolate,
    accentColor: '#6F1D1B',
    fruitType: 'berry',
    available: true,
    stock: 30,
  },
  {
    id: 'vanilla-shake',
    name: 'Vanilla Shake',
    slug: 'vanilla-shake',
    description: 'Smooth Madagascar vanilla bean shake blended with soaked macadamias, cashew milk, and agave syrup.',
    category: 'Shakes',
    price: 189,
    sizePrices: {
      '250ml': 189,
      '500ml': 299,
      '1L': 539,
    },
    ingredients: ['Madagascar Vanilla Bean', 'Soaked Macadamia Nuts', 'Cashew Milk', 'Organic Agave', 'Himalayan Salt'],
    nutrition: {
      calories: 250,
      vitaminC: '10% DV',
      sugar: '14g (Agave)',
      protein: '10g',
      carbs: '28g',
      fiber: '3g',
    },
    healthBenefits: ['Energy', 'Fitness'],
    tags: ['Real Vanilla Bean', 'Nut Milk Blend', 'Silky Smooth'],
    rating: 4.7,
    reviewCount: 120,
    image: SVG_IMAGES.vanilla,
    accentColor: '#FFE5EC',
    fruitType: 'lemon',
    available: true,
    stock: 25,
  },
  {
    id: 'strawberry-shake',
    name: 'Strawberry Shake',
    slug: 'strawberry-shake',
    description: 'Classic rich strawberry shake featuring real berry chunks, vanilla bean cream, and almond crumble top.',
    category: 'Shakes',
    price: 189,
    sizePrices: {
      '250ml': 189,
      '500ml': 299,
      '1L': 539,
    },
    ingredients: ['Real Strawberry Chunks', 'Coconut Whip', 'Almond Milk', 'Madagascar Vanilla', 'Toasted Almond Crumble'],
    nutrition: {
      calories: 235,
      vitaminC: '80% DV',
      sugar: '18g (Natural)',
      protein: '7g',
      carbs: '31g',
      fiber: '4g',
    },
    healthBenefits: ['Refreshment', 'Energy'],
    tags: ['Real Berry Chunks', 'Plant Based', 'Decadent'],
    rating: 4.8,
    reviewCount: 168,
    image: SVG_IMAGES.strawberry,
    accentColor: '#FF4D6D',
    fruitType: 'strawberry',
    available: true,
    stock: 40,
  },
  {
    id: 'mango-shake',
    name: 'Mango Shake',
    slug: 'mango-shake',
    description: 'Thick & dreamy mango shake topped with roasted pistachios, cardamom powder, and fresh mango cubes.',
    category: 'Shakes',
    price: 199,
    sizePrices: {
      '250ml': 199,
      '500ml': 319,
      '1L': 559,
    },
    ingredients: ['Alphonso Mango Slices', 'Condensed Coconut Milk', 'Roasted Pistachios', 'Green Cardamom'],
    nutrition: {
      calories: 275,
      vitaminC: '130% DV',
      sugar: '26g (Natural)',
      protein: '6g',
      carbs: '40g',
      fiber: '4.5g',
    },
    healthBenefits: ['Energy', 'Refreshment'],
    tags: ['Pistachio Topped', 'Thick & Rich', 'Seasonal Best'],
    rating: 4.9,
    reviewCount: 220,
    image: SVG_IMAGES.mango,
    accentColor: '#FF9F1C',
    fruitType: 'mango',
    available: true,
    stock: 50,
  },
  {
    id: 'morning-fresh-combo',
    name: 'Morning Fresh Combo',
    slug: 'morning-fresh-combo',
    description: 'Start your day right! Includes 1 Green Detox (500ml), 1 Orange Glow (500ml), and a complimentary wellness shot.',
    category: 'Combos',
    price: 399,
    sizePrices: {
      '250ml': 399,
      '500ml': 399,
      '1L': 699,
    },
    ingredients: ['Green Detox 500ml', 'Orange Glow 500ml', 'Ginger Immunity Shot 60ml'],
    nutrition: {
      calories: 195,
      vitaminC: '360% DV',
      sugar: '27g (Natural)',
      protein: '5g',
      carbs: '44g',
      fiber: '7.5g',
    },
    healthBenefits: ['Immunity', 'Detox', 'Energy'],
    tags: ['Combo Savings', 'Best Value', 'Daily Morning Pack'],
    rating: 5.0,
    reviewCount: 450,
    image: SVG_IMAGES.orange,
    accentColor: '#38B000',
    fruitType: 'orange',
    available: true,
    stock: 40,
    featured: true,
  },
  {
    id: 'fitness-combo',
    name: 'Fitness Combo',
    slug: 'fitness-combo',
    description: 'Pre and post-workout power bundle: 1 Chocolate Protein Shake (500ml) + 1 Watermelon Hydration Splash (500ml).',
    category: 'Combos',
    price: 449,
    sizePrices: {
      '250ml': 449,
      '500ml': 449,
      '1L': 789,
    },
    ingredients: ['Chocolate Protein Shake 500ml', 'Watermelon Splash 500ml'],
    nutrition: {
      calories: 365,
      vitaminC: '60% DV',
      sugar: '29g (Natural)',
      protein: '22g',
      carbs: '58g',
      fiber: '7g',
    },
    healthBenefits: ['Fitness', 'Hydration', 'Energy'],
    tags: ['Gym Pack', '22g Protein', 'Electrolytes'],
    rating: 4.9,
    reviewCount: 310,
    image: SVG_IMAGES.watermelon,
    accentColor: '#7209B7',
    fruitType: 'watermelon',
    available: true,
    stock: 30,
  },
  {
    id: 'summer-refresh-combo',
    name: 'Summer Refresh Combo',
    slug: 'summer-refresh-combo',
    description: '4-pack party bundle featuring Mango Burst, Watermelon Splash, Pineapple Punch, and Cucumber Mint (250ml each).',
    category: 'Combos',
    price: 469,
    sizePrices: {
      '250ml': 469,
      '500ml': 749,
      '1L': 1299,
    },
    ingredients: ['Mango Burst 250ml', 'Watermelon Splash 250ml', 'Pineapple Punch 250ml', 'Cucumber Mint 250ml'],
    nutrition: {
      calories: 430,
      vitaminC: '335% DV',
      sugar: '60g (Natural)',
      protein: '4.7g',
      carbs: '99g',
      fiber: '9.5g',
    },
    healthBenefits: ['Refreshment', 'Hydration', 'Immunity'],
    tags: ['4-Pack Bundle', 'Save 20%', 'Party Favorite'],
    rating: 4.9,
    reviewCount: 520,
    image: SVG_IMAGES.mango,
    accentColor: '#FF9F1C',
    fruitType: 'mango',
    available: true,
    stock: 60,
    featured: true,
  },
];
